apiVersion: app/v1
kind: Deployment
metadata:
  name: survey-app-deploy
  namespace: python-app
  labales:
    app: survey-app
spec:
  selector:
    matchLabels:
      app: survey-app
  replicas: 2
  templete:
    metadata:
      labels:
        app: survey-app
    
    spec:
      containers:
      - name: survey-app
        image: abdullahmarey/full-proj:latest
        ports:
        - containerPort: 8000

