version: "3.8"
services:
  app: 
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "5000:8000"
    volumes:
      - .:/home/app
      
    environment:
      - DATABASE_URL=sqlite:////usr/src/app/db/data.sqlite3

